name: 编译

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        target:
          #- x86_64-pc-windows-gnu
          #- x86_64-pc-windows-gnullvm
          - x86_64-pc-windows-msvc
    name: Windows-${{ matrix.target }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: 构建项目
        run: cargo build --release --target=${{ matrix.target }}

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: wget-rs-windows-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/wget-rs.exe

  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          #- x86_64-unknown-linux-gnux32
          #- x86_64-unknown-linux-musl
    name: Linux-${{ matrix.target }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: 构建项目
        run: cargo build --release --target=${{ matrix.target }}

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: wget-rs-windows-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/wget-rs
